version: '3.3'
services:
  top-articles-service:
    build:
      context: ./backend/top-articles-service
    ports:
      - "8000:8000"

  group-articles-service:
    build:
      context: ./backend/article-grouping-service
    ports:
      - "8001:8001"
    depends_on:
      - top-articles-service

  enrich-article-service:
    build:
      context: ./backend/web-scraping-service
    ports:
      - "8002:8002"
    depends_on:
      - group-articles-service

  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service 
  auth-service:
    build: 
      context: ./backend
    ports:
      - "5001:5001"


  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - top-articles-service
      - group-articles-service
      - enrich-article-service
