version: '3.3'
services:
  top-articles-service:
    build:
      context: ./top-articles-service
    ports:
      - "8000:8000"

  group-articles-service:
    build:
      context: ./article-grouping-service
    ports:
      - "8001:8001"
    depends_on:
      - top-articles-service
